[server]
# Server configuration
maxUploadSize = 200
# Remove CORS/XSRF conflict - let Streamlit handle defaults
# enableCORS = false
# enableXsrfProtection = true

[client]
# Client configuration
showErrorDetails = true
toolbarMode = "viewer"

[theme]
# App theme (optional - Streamlit will use default)
# primaryColor = "#FF6B6B"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730" 